-- SUB QUERIES AND CTES
-- SUB QUERY IS QUERY INSIDE ANOTHER QUERY

-- FIRST FIND SOMETHING
-- THEN USE THAT RESULT IN ANOTHER QUERY

-- FIND EMPLOYEES WHO EARN MORE THAN THE AVERAGE SALARY

-- 1 FIND AVERAGE SALARY
SELECT ROUND(AVG(salary),2)
FROM employees;

-- USE THIS QUERY INSIDE ANOTHER QUERY
SELECT emp_name, salary
FROM employees
WHERE salary > (
SELECT ROUND(AVG(salary),2)
FROM employees
);