-- AGGREGATE FUNCTIONS COUNT, SUM, AVG WORK ON GROUP OF ROWS
-- GROUP SIMILAR ROWS TOGETHER, THEN CALCULATE SOMETHING FOR EACH GROUP

-- HOW MANY EMPLOYEES ARE IN EACH DEPARTMENT
SELECT department, COUNT(*) AS total_employees
FROM employees
GROUP BY department;

-- AVERAGE SALARY PER DEPARTMENT
SELECT department, ROUND(AVG(salary),2) AS avg_salary
FROM employees
GROUP BY department;

-- EMPLOYEE PER DEPARTMENT (SALARY > 60K)
SELECT department, COUNT(*) AS count_emp
FROM employees
WHERE salary > 60000
GROUP BY department;



