-- HAVING FILTERING GROUPS (NOT ROWS)

-- SHOW ONLY DEPARTMENT WITH AVERAGE SALARY > 65000
SELECT department, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING AVG(salary) > 65000;

-- WHERE			VS			HAVING
-- FILTER ROWS   				FILTER GROUPS
-- BEFORE GROUP BY 				AFTER GROUP BY
-- CONNOT USE AGGREGATES 		USES AGGREGATES

-- MULTIPLE GROUPING COLUMNS
-- EMPLOYEE PER DEPARTMENT AND JOB TITLE
SELECT department, job_title, COUNT(*) AS total
FROM employees
GROUP BY department ,job_title;

