-- AGGREGATE FUNCTIONS
-- COLLAPSE MULTIPLE ROWS INTO A SINGLE ROW

-- INSTEAD OF: SHOW ME ALL EMPLOYEES 
-- YOU ASK: TELL ME SOMETHING ABOUT ALL EMPLOYEES

-- TOTAL NO OF EMPLOYEES
SELECT COUNT(*)
AS total_employees
FROM employees;

-- COUNT EMPLOYEES IN IT DEPARTMENT
SELECT COUNT(*)
AS it_employees
FROM employees
WHERE department = 'IT';



